chore: minor change

diff --git a/.github/workflows/lstm-workflow.yml b/.github/workflows/lstm-workflow.yml
--- a/.github/workflows/lstm-workflow.yml
+++ b/.github/workflows/lstm-workflow.yml
@@ -25,10 +25,28 @@ jobs:
       run: |
         docker run --name lstm-container -d lstm-script
 
+    - name: Check container logs
+      run: |
+        docker logs lstm-container
+
+    - name: Check container file structure
+      run: |
+        docker exec lstm-container ls -l /app/algorithm
+
+    - name: Ensure SQLite file exists
+      run: |
+        if docker exec lstm-container test -f /app/algorithm/lstm_predictions.sqlite3; then
+          echo "Database file found.";
+        else
+          echo "Database file NOT found. Available files are as follows:";
+          docker exec lstm-container ls -l /app/algorithm;
+          exit 1;
+        fi
+
     - name: Copy SQLite file from container
       run: |
         docker cp lstm-container:/app/algorithm/lstm_predictions.sqlite3 algorithm/
-        
+
     - name: Commit and Push SQLite Database file to GitHub
       run: |
         git config --global user.name "github-actions"
